Document: repeater-start
Title: Debian repeater-start Manual
Author: <insert document author here>
Abstract: This manual describes what repeater-start is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/repeater-start/repeater-start.sgml.gz

Format: postscript
Files: /usr/share/doc/repeater-start/repeater-start.ps.gz

Format: text
Files: /usr/share/doc/repeater-start/repeater-start.text.gz

Format: HTML
Index: /usr/share/doc/repeater-start/html/index.html
Files: /usr/share/doc/repeater-start/html/*.html
